### ISSUE TITLE
[BUG] CSS rules broke on screen (21" and more?)

### ISSUE THREAD

**Issue by Mara-Li** [danielo515/obsidian-modal-form#290]
**Describe the bug**
The template edit form is unscrollable when Obsidian take my entire screen.

**To Reproduce**
Have a screen at 21".

**Expected behavior**
Able of scrolling

**Additional context**
The bug is caused by this css rules:
```css
@media (min-width: 100rem) {
    form.svelte-8lqyxl {
        display: flex;
        flex-direction: column;
        height: 100%;
        overflow: hidden;
    }
```
